/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package training;

public class App {
    public String getGreeting() {
        return "Hello consortium world.";
    }

    public static void main(String[] args) { Rectangle r = new Rectangle(10, 4);
        Square s = new Square(7);
        Circle c = new Circle(3.5);

        System.out.println("Rectangle Area : " + r.getArea());
        System.out.println("Square Area : " + s.getArea());
        System.out.println("Circle Area : " + c.getArea());
        System.out.println();

        System.out.println(new App().getGreeting());

    }
}
abstract class Shapes
{
    double l,b,s,r;
   abstract double getArea();

}

class Rectangle extends Shapes
{

    Rectangle(double l, double b)
    {
        this.l = l;
        this.b = b;
    }

    double getArea()
    {
        return l * b;
    }
}

class Square  extends Shapes
{

    Square(double s)
    {
        this.s = s;
    }

    double getArea()
    {
        return s * s;
    }
}

class Circle extends Shapes
{


    Circle(double r)
    {
        this.r = r;
    }

    double getArea()
    {
        return (22.0/7.0) * r * r;
    }
}
