  
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package training;


import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello consortium world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new Area().getAreaforAllShapes());
        System.out.println((Arrays.toString(new Employees().getTheName())));
    }
}
